Add version arg and fix help menu

diff --git a/synonym b/synonym
--- a/synonym
+++ b/synonym
@@ -20,40 +20,54 @@
 
 help() {
     printf "
-       .--.    _   __  _ .--.   .--.   _ .--.    _   __  _ .--..--.
-      ( (\`\]  [ \ [  ][ \`.-. |/ .'\`\ \[ \`.-. |  [ \ [  ][ \`.-. .-. |
-       \`'.'.   \ '/ /  | | | || \__. | | | | |   \ '/ /  | | | | | |
-      [\__) )[\_:  /  [___||__]'.__.' [___||__][\_:  /  [___||__||__]
-              \__.'                             \__.'
+  .--.    _   __  _ .--.   .--.   _ .--.    _   __  _ .--..--.
+ ( (\`\]  [ \ [  ][ \`.-. |/ .'\`\ \[ \`.-. |  [ \ [  ][ \`.-. .-. |
+  \`'.'.   \ '/ /  | | | || \__. | | | | |   \ '/ /  | | | | | |
+ [\__) )[\_:  /  [___||__]'.__.' [___||__][\_:  /  [___||__||__]
+         \__.'                             \__.'
 
-     synonym is a small utility tool to rapidly find synonyms directly
-     from your terminal.
+synonym is a small utility tool to rapidly find synonyms directly
+from your terminal.
 
-     The script is fetching https://www.thesaurus.com/ rest API.
-     List of languages available: en, fr, cs, el, es, da, de, hu, it,
-     no, pl, pt, ro, ru, sk
+The script is fetching https://www.thesaurus.com/ rest API.
+List of languages available: en, fr, cs, el, es, da, de, hu, it,
+no, pl, pt, ro, ru, sk
 
-     You will need to generate an API key to use this script, you can
-     do so at https://thesaurus.altervista.org/mykey
+You will need to generate an API key to use this script, you can
+do so at https://thesaurus.altervista.org/mykey
 
-     You will also need to install jq if you don't have it already
-     https://stedolan.github.io/jq/download/
+You will also need to install jq if you don't have it already
+https://stedolan.github.io/jq/download/
 
-     Created by Matthieu Petiteau <mpetiteau.pro@gmail.com>
+Created by Matthieu Petiteau <mpetiteau.pro@gmail.com>
+\n"
+}
 
-     USAGE
-     -----------------------------------------------------------------
-     synonym <word>               Finds all synonyms for this specific
-                                  word in the default language.
+usage() {
+    printf "
+USAGE
+-----------------------------------------------------------------
+positional arguments:
+    WORD
+    synonym <word>           Finds all synonyms for this specific
+                             word in the default language.
 
-     synonym -l <lang> <word>     Finds all synonyms for this specific
-                                  word in this specific language.
-                                  (en, fr, cs, el, es, da, de, hu, it,
-                                  no, pl, pt, ro, ru, sk)
+optionnal arguments:
+    -l LANG
+    synonym -l <lang> <word> Finds all synonyms for this specific
+                             word in this specific language.
+                             (en, fr, cs, el, es, da, de, hu, it,
+                             no, pl, pt, ro, ru, sk)
+    -v
+    synonym -v               Show program version number and exit.
 
-     synonym -h                   Show this help message and exit.
+    -h
+    synonym -h               Show this help message and exit.
+\n"
+}
 
-    \n"
+version() {
+    printf "synonym v1.0 (Matthieu Petiteau)\n"
 }
 
 # request API
@@ -124,12 +138,13 @@ for d in "${conf_dir[@]}"; do
 done
 
 # Args
-options=":l:h"
+options=":l:hv"
 while getopts "$options" option; do
     case "${option}" in
         l  ) language_index ${OPTARG};;
-        h  ) help; exit 0;;
-        \? ) printf "Error: invalid option: -${OPTARG}\n" >&2; exit 1;;
+        h  ) help; version; usage; exit 0;;
+        v  ) version; exit 0;;
+        \? ) printf "Error: invalid option: -${OPTARG}\n" >&2; usage; exit 1;;
     esac
 done
 
@@ -137,8 +152,8 @@ shift $((OPTIND - 1))
 WORD=$1
 
 # Check mandatory args
-if [ -z $WORD ]; then printf "Error: please specific a word\n"; exit 1; fi
-if [ -z $KEY ]; then printf "Error: api key not found in synonymrc\n"; exit 1; fi
+if [ -z $WORD ]; then printf "Error: please specific a word\n"; usage; exit 1; fi
+if [ -z $KEY ]; then printf "Error: api key not found in synonymrc\n"; usage; exit 1; fi
 
 # Pick language
 if [ -z $SYN_LANG ]; then
