Rewrite some things

diff --git a/synonym b/synonym
--- a/synonym
+++ b/synonym
@@ -17,8 +17,10 @@
 # You will also need a Thesaurus API key provided
 # at https://thesaurus.altervista.org/mykey
 #
+self=${0##*/}
+version="v1.1 (Matthieu Petiteau)"
 
-help() {
+showinfo() {
     printf "
   .--.    _   __  _ .--.   .--.   _ .--.    _   __  _ .--..--.
  ( (\`\]  [ \ [  ][ \`.-. |/ .'\`\ \[ \`.-. |  [ \ [  ][ \`.-. .-. |
@@ -26,7 +28,7 @@ help() {
  [\__) )[\_:  /  [___||__]'.__.' [___||__][\_:  /  [___||__||__]
          \__.'                             \__.'
 
-synonym is a small utility tool to rapidly find synonyms directly
+$self is a small utility tool to rapidly find synonyms directly
 from your terminal.
 
 The script is fetching https://www.thesaurus.com/ rest API.
@@ -43,31 +45,23 @@ Created by Matthieu Petiteau <mpetiteau.pro@gmail.com>
 \n"
 }
 
-usage() {
-    printf "
-USAGE
------------------------------------------------------------------
-positional arguments:
-    WORD
-    synonym <word>           Finds all synonyms for this specific
-                             word in the default language.
-
-optionnal arguments:
-    -l LANG
-    synonym -l <lang> <word> Finds all synonyms for this specific
-                             word in this specific language.
-                             (en, fr, cs, el, es, da, de, hu, it,
-                             no, pl, pt, ro, ru, sk)
-    -v
-    synonym -v               Show program version number and exit.
-
-    -h
-    synonym -h               Show this help message and exit.
-\n"
+version() {
+    printf "$self $version\n";
 }
 
-version() {
-    printf "synonym v1.0 (Matthieu Petiteau)\n"
+usage() {
+    printf "
+Usage: $self [OPTION] [WORD]
+Finds all synonyms for a specific word in the language selected
+or the default one.
+
+Options:
+  -l LANG      Finds all synonyms for this specific language.
+               Languages supported: en, fr, cs, el, es, da, de,
+               hu, it, no, pl, pt, ro, ru, sk
+  -v           Show program version number and exit.
+  -h           Show help message and exit.
+\n"
 }
 
 # request API
@@ -146,9 +140,9 @@ options=":l:hv"
 while getopts "$options" option; do
     case "${option}" in
         l  ) language_index ${OPTARG};;
-        h  ) help; version; usage; exit 0;;
+        h  ) showinfo; version; usage; exit 0;;
         v  ) version; exit 0;;
-        \? ) printf "Error: invalid option: -${OPTARG}\n" >&2; usage; exit 1;;
+        \? ) printf "Error: invalid option: -${OPTARG}\n" >&2; exit 1;;
     esac
 done
 
@@ -156,7 +150,7 @@ shift $((OPTIND - 1))
 WORD=$1
 
 # Check mandatory args
-if [ -z $WORD ]; then printf "Error: please specific a word\n"; usage; exit 1; fi
+if [ -z $WORD ]; then printf "Error: please specific a word\n"; exit 1; fi
 if [ -z $KEY ]; then printf "Error: api key not found in synonymrc\n"; exit 1; fi
 
 # Pick language
